import { type Metadata } from 'next'
import './globals.css'
import { Roboto_Flex, Bai_Jamjuree } from 'next/font/google'
import { type ReactNode } from 'react'

const roboto = Roboto_Flex({ subsets: ['latin'], variable: '--font-roboto' })
const baiJamjuee = Bai_Jamjuree({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-bai-jamjuree',
})

export const metadata: Metadata = {
  title: '🚀 Spacetime',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${baiJamjuee.variable} font-roboto text-gray-100`}
      >
        {children}
      </body>
    </html>
  )
}
